# Generated by Django 5.0.2 on 2024-03-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummonerPuuid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freshBlood', models.BooleanField(default=False)),
                ('hotStreak', models.BooleanField(default=False)),
                ('inactive', models.BooleanField(default=False)),
                ('leagueId', models.CharField(max_length=100)),
                ('leaguePoints', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('puuid', models.CharField(max_length=100)),
                ('queueType', models.CharField(default='RANKED_TFT', max_length=100)),
                ('rank', models.CharField(default='I', max_length=100)),
                ('summonerId', models.CharField(default='', max_length=100)),
                ('summonerName', models.CharField(default='', max_length=100)),
                ('tier', models.CharField(default='IRON', max_length=100)),
                ('veteran', models.BooleanField(default=False)),
                ('wins', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
