# Generated by Django 5.0.2 on 2024-03-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summonerpuuid',
            old_name='leagueId',
            new_name='accountId',
        ),
        migrations.RenameField(
            model_name='summonerpuuid',
            old_name='leaguePoints',
            new_name='profileIconId',
        ),
        migrations.RenameField(
            model_name='summonerpuuid',
            old_name='losses',
            new_name='revisionDate',
        ),
        migrations.RenameField(
            model_name='summonerpuuid',
            old_name='wins',
            new_name='summonerLevel',
        ),
        migrations.RemoveField(
            model_name='summonerpuuid',
            name='freshBlood',
        ),
        migrations.RemoveField(
            model_name='summonerpuuid',
            name='hotStreak',
        ),
        migrations.RemoveField(
            model_name='summonerpuuid',
            name='inactive',
        ),
        migrations.RemoveField(
            model_name='summonerpuuid',
            name='queueType',
        ),
        migrations.RemoveField(
            model_name='summonerpuuid',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='summonerpuuid',
            name='summonerId',
        ),
        migrations.RemoveField(
            model_name='summonerpuuid',
            name='summonerName',
        ),
        migrations.RemoveField(
            model_name='summonerpuuid',
            name='tier',
        ),
        migrations.RemoveField(
            model_name='summonerpuuid',
            name='veteran',
        ),
        migrations.AddField(
            model_name='summonerpuuid',
            name='name',
            field=models.CharField(default='소환사닉네임', max_length=30),
        ),
        migrations.AlterField(
            model_name='summonerpuuid',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
