# Generated by Django 5.0.2 on 2024-05-21 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summonerpuuid',
            name='accountId',
        ),
        migrations.RemoveField(
            model_name='summonerpuuid',
            name='id',
        ),
        migrations.RemoveField(
            model_name='summonerpuuid',
            name='name',
        ),
        migrations.RemoveField(
            model_name='summonerpuuid',
            name='profileIconId',
        ),
        migrations.RemoveField(
            model_name='summonerpuuid',
            name='revisionDate',
        ),
        migrations.RemoveField(
            model_name='summonerpuuid',
            name='summonerLevel',
        ),
        migrations.AddField(
            model_name='summonerpuuid',
            name='gameName',
            field=models.CharField(default='hide on bush', max_length=40),
        ),
        migrations.AddField(
            model_name='summonerpuuid',
            name='tagLine',
            field=models.CharField(default='KR1', max_length=20),
        ),
        migrations.AlterField(
            model_name='summonermatchesbypuuid',
            name='summoner_puuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='profiles.summonerpuuid'),
        ),
        migrations.AlterField(
            model_name='summonerpuuid',
            name='puuid',
            field=models.TextField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
