# Generated by Django 5.0.2 on 2024-03-30 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_leagueid_summonerpuuid_accountid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummonerMatchesByPuuid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=100)),
                ('summoner_puuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.summonerpuuid')),
            ],
        ),
    ]
