# Generated by Django 5.0.2 on 2024-05-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_summonerpuuid_accountid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summonerpuuid',
            name='accountId',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='summonerpuuid',
            name='profileIconId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summonerpuuid',
            name='summonerId',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='summonerpuuid',
            name='summonerLevel',
            field=models.IntegerField(null=True),
        ),
    ]
