# Generated by Django 4.0.10 on 2024-08-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_summonerpuuid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summonerpuuid',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
