# Generated by Django 5.0.2 on 2024-05-26 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_summonerpuuid_accountid_summonerpuuid_profileiconid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueEntryDTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=60, null=True)),
                ('leagueId', models.CharField(max_length=60, null=True)),
                ('queueType', models.CharField(max_length=30)),
                ('tier', models.CharField(max_length=30, null=True)),
                ('rank', models.CharField(max_length=30, null=True)),
                ('leaguePoints', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('veteran', models.BooleanField(default=False)),
                ('inactive', models.BooleanField(default=False)),
                ('freshBlood', models.BooleanField(default=False)),
                ('hotStreak', models.BooleanField(default=False)),
                ('summonerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_entry_summonerId', to='profiles.summonerpuuid')),
            ],
        ),
    ]
