# Generated by Django 5.0.2 on 2024-04-06 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_summonermatchesbypuuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summonermatchesbypuuid',
            name='summoner_puuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.summonerpuuid', to_field='puuid'),
        ),
        migrations.AlterField(
            model_name='summonerpuuid',
            name='puuid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
