# Generated by Django 4.0.10 on 2024-09-06 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_summonerpuuid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summonerpuuid',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='SummonerBadMatchesByPuuid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=100)),
                ('summoner_puuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bad_matches', to='profiles.summonerpuuid', to_field='puuid')),
            ],
        ),
    ]
