# Generated by Django 5.0.2 on 2024-05-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_leagueentrydto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueentrydto',
            name='leagueId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leagueentrydto',
            name='puuid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leagueentrydto',
            name='queueType',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leagueentrydto',
            name='summonerId',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='summonerpuuid',
            name='accountId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='summonerpuuid',
            name='gameName',
            field=models.CharField(default='hide on bush', max_length=200),
        ),
        migrations.AlterField(
            model_name='summonerpuuid',
            name='summonerId',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
