# Generated by Django 5.0.2 on 2024-04-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_augment_companion_traits_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summonermatchbymatchid',
            name='match_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='summonermatchesbypuuid',
            name='match_id',
            field=models.CharField(max_length=100),
        ),
    ]
