# Generated by Django 4.0.10 on 2024-08-08 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_leagueentrydto_leagueid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summonerpuuid',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summonermatchesbypuuid',
            name='summoner_puuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='profiles.summonerpuuid', to_field='puuid'),
        ),
        migrations.AlterField(
            model_name='summonerpuuid',
            name='puuid',
            field=models.TextField(max_length=200, unique=True),
        ),
    ]
