# Generated by Django 5.0.2 on 2024-04-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_summonermatchbymatchid_match_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDetailsByMatchId',
            fields=[
                ('match_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('match_detail', models.JSONField(default=dict, verbose_name='json')),
            ],
        ),
    ]
