# Generated by Django 5.0.2 on 2024-05-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('ingameKey', models.CharField(default='inGameKey', max_length=70, primary_key=True, serialize=False)),
                ('encounterDesc', models.TextField(default='조우자 설명', max_length=1000)),
                ('name', models.CharField(max_length=20)),
                ('tileImageUrl', models.URLField(default='//cdn.lolchess.gg/upload/images/champions/Aatrox_1709255107-Aatrox.jpg')),
            ],
        ),
    ]
