# Generated by Django 5.0.2 on 2024-05-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='description_1',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='description_4',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='id',
        ),
        migrations.AddField(
            model_name='encounter',
            name='encounterDesc',
            field=models.TextField(default='조우자 설명', max_length=500),
        ),
        migrations.AddField(
            model_name='encounter',
            name='ingameKey',
            field=models.CharField(default='inGameKey', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='encounter',
            name='tileImageUrl',
            field=models.URLField(default='//cdn.lolchess.gg/upload/images/champions/Aatrox_1709255107-Aatrox.jpg'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
