# Generated by Django 5.0.2 on 2024-03-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='augment',
            name='tier',
            field=models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('prismatic', 'Prismatic')], default='silver', max_length=10),
        ),
    ]
