# Generated by Django 5.0.2 on 2024-03-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augments', '0002_augment_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='augment',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
