# Generated by Django 5.0.2 on 2024-05-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augments', '0004_remove_augment_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='augment',
            old_name='description',
            new_name='desc',
        ),
        migrations.AddField(
            model_name='augment',
            name='championIngameKey',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='augment',
            name='imageUrl',
            field=models.URLField(default='//cdn.lolchess.gg/upload/images/items/ACutAbove_1685417489-A-Cut-Above-II.TFT_Set9.png'),
        ),
        migrations.AddField(
            model_name='augment',
            name='ingameKey',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='augment',
            name='isHidden',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='augment',
            name='isNew',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='augment',
            name='key',
            field=models.CharField(default='Eng_Key', max_length=20),
        ),
        migrations.AddField(
            model_name='augment',
            name='legendCode1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='augment',
            name='legendCode2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='augment',
            name='tag1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='augment',
            name='tag2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='augment',
            name='tier',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
