# Generated by Django 5.0.2 on 2024-05-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augments', '0005_rename_description_augment_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='augment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='augment',
            name='isNew',
        ),
        migrations.AlterField(
            model_name='augment',
            name='championIngameKey',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='augment',
            name='desc',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='augment',
            name='imageUrl',
            field=models.URLField(default='https://cdn.lolchess.gg/upload/images/items/ACutAbove_1685417489-A-Cut-Above-II.TFT_Set9.png'),
        ),
        migrations.AlterField(
            model_name='augment',
            name='ingameKey',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='augment',
            name='isHidden',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='augment',
            name='key',
            field=models.CharField(default='Eng_Key', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='augment',
            name='legendCode1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='augment',
            name='legendCode2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='augment',
            name='tag2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
