# Generated by Django 5.0.2 on 2024-05-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augments', '0006_remove_augment_id_remove_augment_isnew_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='augment',
            name='championIngameKey',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='augment',
            name='ingameKey',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='augment',
            name='key',
            field=models.CharField(default='Eng_Key', max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='augment',
            name='legendCode1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='augment',
            name='legendCode2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='augment',
            name='tag1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='augment',
            name='tag2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
