# Generated by Django 5.0.2 on 2024-07-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augments', '0007_alter_augment_championingamekey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='augment',
            name='desc',
            field=models.TextField(max_length=300),
        ),
    ]
