# Generated by Django 5.0.2 on 2024-07-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augments', '0008_alter_augment_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set11Augment',
            fields=[
                ('key', models.CharField(default='Eng_Key', max_length=40, primary_key=True, serialize=False)),
                ('ingameKey', models.CharField(max_length=70, null=True)),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField(max_length=300)),
                ('imageUrl', models.URLField(default='https://cdn.lolchess.gg/upload/images/items/ACutAbove_1685417489-A-Cut-Above-II.TFT_Set9.png')),
                ('isHidden', models.BooleanField(blank=True, null=True)),
                ('tier', models.PositiveIntegerField(default=1)),
                ('championIngameKey', models.CharField(blank=True, max_length=20, null=True)),
                ('legendCode1', models.CharField(blank=True, max_length=30, null=True)),
                ('legendCode2', models.CharField(blank=True, max_length=30, null=True)),
                ('tag1', models.CharField(blank=True, max_length=30, null=True)),
                ('tag2', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Set12Augment',
            fields=[
                ('key', models.CharField(default='Eng_Key', max_length=40, primary_key=True, serialize=False)),
                ('ingameKey', models.CharField(max_length=70, null=True)),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField(max_length=300)),
                ('imageUrl', models.URLField(default='https://cdn.lolchess.gg/upload/images/items/ACutAbove_1685417489-A-Cut-Above-II.TFT_Set9.png')),
                ('isHidden', models.BooleanField(blank=True, null=True)),
                ('tier', models.PositiveIntegerField(default=1)),
                ('championIngameKey', models.CharField(blank=True, max_length=20, null=True)),
                ('legendCode1', models.CharField(blank=True, max_length=30, null=True)),
                ('legendCode2', models.CharField(blank=True, max_length=30, null=True)),
                ('tag1', models.CharField(blank=True, max_length=30, null=True)),
                ('tag2', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Augment',
        ),
    ]
