# Generated by Django 4.0.10 on 2024-09-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augments', '0009_set11augment_set12augment_delete_augment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set12augment',
            name='tag1',
        ),
        migrations.RemoveField(
            model_name='set12augment',
            name='tag2',
        ),
        migrations.AlterField(
            model_name='set12augment',
            name='isHidden',
            field=models.BooleanField(default=False),
        ),
    ]
