# Generated by Django 5.0.2 on 2024-04-30 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_type', models.CharField(choices=[('champ', 'Champ'), ('combat', 'Combat'), ('spatula', 'Spatula'), ('coin', 'Coin'), ('card', 'Card'), ('item', 'Item')], default='champ', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('portal_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portals.portaltype')),
            ],
        ),
    ]
