# Generated by Django 5.0.2 on 2024-05-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='_type',
            field=models.CharField(default='Augments', max_length=10),
        ),
        migrations.AlterField(
            model_name='portal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
