# Generated by Django 5.0.2 on 2024-03-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='portal_type',
            field=models.CharField(choices=[('champ', 'Champ'), ('combat', 'Combat'), ('spatula', 'Spatula'), ('coin', 'Coin'), ('card', 'Card'), ('item', 'Item')], default='champ', max_length=10),
        ),
    ]
