# Generated by Django 5.0.2 on 2024-07-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0002_portal__type_alter_portal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set11Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(default='Augments', max_length=10)),
                ('_key', models.CharField(default='TFT_Portals_Augments_GoldThird', max_length=100)),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField(default='이번 게임에서 얻는 마지막 증강이 골드 티어가 됩니다.', max_length=300)),
                ('iconImageUrl', models.URLField(default='https://s-tft-api.op.gg/img/set/11/tft-region-portal/augmentcards_icon.png')),
            ],
        ),
        migrations.CreateModel(
            name='Set12Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(default='Augments', max_length=10)),
                ('_key', models.CharField(default='TFT_Portals_Augments_GoldThird', max_length=100)),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField(default='이번 게임에서 얻는 마지막 증강이 골드 티어가 됩니다.', max_length=300)),
                ('iconImageUrl', models.URLField(default='https://s-tft-api.op.gg/img/set/11/tft-region-portal/augmentcards_icon.png')),
            ],
        ),
        migrations.DeleteModel(
            name='Portal',
        ),
    ]
