# Generated by Django 5.0.2 on 2024-03-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0006_rename_portal_type_portaltype_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portaltype',
            name='type',
        ),
        migrations.AddField(
            model_name='portaltype',
            name='portaltype',
            field=models.CharField(choices=[('champ', 'Champ'), ('combat', 'Combat'), ('spatula', 'Spatula'), ('coin', 'Coin'), ('card', 'Card'), ('item', 'Item')], default='champ', max_length=10),
        ),
    ]
