# Generated by Django 5.0.2 on 2024-03-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0007_remove_portaltype_type_portaltype_portaltype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portaltype',
            old_name='portaltype',
            new_name='portal_type',
        ),
    ]
