# Generated by Django 5.0.2 on 2024-04-30 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SynergyStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack', models.CharField(choices=[('1', '1'), ('2/4', '2/4'), ('2/3/4', '2/3/4'), ('2/3/4/5', '2/3/4/5'), ('2/4/6', '2/4/6'), ('2/4/6/8', '2/4/6/8'), ('2/3/4/5/6/7', '2/3/4/5/6/7'), ('3/5', '3/5'), ('3/5/7', '3/5/7'), ('3/5/7/10', '3/5/7/10')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SynergyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('b/s/g', 'B/S/G'), ('b/g/p', 'B/G/P'), ('b/s/g/p', 'B/S/G/P'), ('b/s/s/s/g/g', 'B/S/S/G/G'), ('b/g', 'B/G'), ('unique', 'UNIQUE'), ('none', 'NONE')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('effect_1', models.TextField(blank=True, null=True)),
                ('effect_2', models.TextField(blank=True, null=True)),
                ('effect_3', models.TextField(blank=True, null=True)),
                ('effect_4', models.TextField(blank=True, null=True)),
                ('effect_5', models.TextField(blank=True, null=True)),
                ('effect_6', models.TextField(blank=True, null=True)),
                ('stack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='synergies.synergystack')),
                ('tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='synergies.synergytier')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('effect_1', models.TextField(blank=True, null=True)),
                ('effect_2', models.TextField(blank=True, null=True)),
                ('effect_3', models.TextField(blank=True, null=True)),
                ('effect_4', models.TextField(blank=True, null=True)),
                ('stack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='synergies.synergystack')),
                ('tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='synergies.synergytier')),
            ],
        ),
    ]
