# Generated by Django 5.0.2 on 2024-05-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('key', models.CharField(default='Eng_Key', max_length=20, primary_key=True, serialize=False)),
                ('ingameKey', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, max_length=300)),
                ('imageUrl', models.URLField(default='//cdn.lolchess.gg/upload/images/traits/Bruiser_normal_1709371605-bruiser.svg')),
                ('blackImageUrl', models.URLField(default='//cdn.lolchess.gg/upload/images/traits/Bruiser_black_1709371605-bruiser.svg')),
                ('whiteImageUrl', models.URLField(default='//cdn.lolchess.gg/upload/images/traits/Bruiser_white_1709371605-bruiser.svg')),
                ('_type', models.CharField(max_length=6)),
                ('style1', models.CharField(max_length=6)),
                ('style1_min', models.PositiveIntegerField(default=1)),
                ('style1_max', models.PositiveIntegerField(default=1, null=True)),
                ('style2', models.CharField(max_length=6)),
                ('style2_min', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('style2_max', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('style3', models.CharField(max_length=6)),
                ('style3_min', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('style3_max', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('stats_1', models.TextField(blank=True, null=True)),
                ('stats_2', models.TextField(blank=True, null=True)),
                ('stats_3', models.TextField(blank=True, null=True)),
                ('stats_4', models.TextField(blank=True, null=True)),
                ('stats_5', models.TextField(blank=True, null=True)),
                ('stats_6', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='origin',
            name='stack',
        ),
        migrations.RemoveField(
            model_name='origin',
            name='tier',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='SynergyStack',
        ),
        migrations.DeleteModel(
            name='Origin',
        ),
        migrations.DeleteModel(
            name='SynergyTier',
        ),
    ]
