# Generated by Django 5.0.2 on 2024-03-05 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synergies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='champion',
        ),
        migrations.RemoveField(
            model_name='origin',
            name='champion',
        ),
    ]
