# Generated by Django 5.0.2 on 2024-03-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synergies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='synergy',
            options={'verbose_name_plural': 'Synergies'},
        ),
    ]
