# Generated by Django 5.0.2 on 2024-03-05 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0005_skill_max_mana_skill_start_mana'),
        ('synergies', '0002_remove_job_champion_remove_origin_champion'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='champion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='champions.champion'),
        ),
        migrations.AddField(
            model_name='origin',
            name='champion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origins', to='champions.champion'),
        ),
    ]
