# Generated by Django 5.0.2 on 2024-05-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergies', '0002_trait_remove_origin_stack_remove_origin_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='style4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trait',
            name='style4_max',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='style2',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='style3',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
