# Generated by Django 5.0.2 on 2024-03-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0005_skill_max_mana_skill_start_mana'),
        ('synergies', '0003_job_champion_origin_champion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='champion',
        ),
        migrations.RemoveField(
            model_name='origin',
            name='champion',
        ),
        migrations.AddField(
            model_name='job',
            name='champion',
            field=models.ManyToManyField(null=True, related_name='jobs', to='champions.champion'),
        ),
        migrations.AddField(
            model_name='origin',
            name='champion',
            field=models.ManyToManyField(null=True, related_name='origins', to='champions.champion'),
        ),
    ]
