# Generated by Django 5.0.2 on 2024-05-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergies', '0003_trait_style4_trait_style4_max_alter_trait_style2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trait',
            name='style4_max',
        ),
        migrations.AddField(
            model_name='trait',
            name='style4_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='style2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
