# Generated by Django 5.0.2 on 2024-05-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergies', '0004_remove_trait_style4_max_trait_style4_min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trait',
            name='stats_1',
        ),
        migrations.RemoveField(
            model_name='trait',
            name='stats_2',
        ),
        migrations.RemoveField(
            model_name='trait',
            name='stats_3',
        ),
        migrations.RemoveField(
            model_name='trait',
            name='stats_4',
        ),
        migrations.RemoveField(
            model_name='trait',
            name='stats_5',
        ),
        migrations.RemoveField(
            model_name='trait',
            name='stats_6',
        ),
        migrations.AddField(
            model_name='trait',
            name='stats1',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trait',
            name='stats2',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trait',
            name='stats3',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trait',
            name='stats4',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trait',
            name='stats5',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trait',
            name='stats6',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='blackImageUrl',
            field=models.URLField(default='https://cdn.lolchess.gg/upload/images/traits/Arcanist_black_1709371622-arcanist.svg'),
        ),
        migrations.AlterField(
            model_name='trait',
            name='imageUrl',
            field=models.URLField(default='https://cdn.lolchess.gg/upload/images/traits/Arcanist_normal_1709371622-arcanist.svg'),
        ),
        migrations.AlterField(
            model_name='trait',
            name='ingameKey',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trait',
            name='key',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trait',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='trait',
            name='style1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='trait',
            name='style1_max',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='style3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='style4_min',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='whiteImageUrl',
            field=models.URLField(default='https://cdn.lolchess.gg/upload/images/traits/Arcanist_white_1709371623-arcanist.svg'),
        ),
    ]
