# Generated by Django 5.0.2 on 2024-03-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0006_remove_champion_dps'),
        ('synergies', '0004_remove_job_champion_remove_origin_champion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='champion',
            field=models.ManyToManyField(related_name='jobs', to='champions.champion'),
        ),
        migrations.AlterField(
            model_name='origin',
            name='champion',
            field=models.ManyToManyField(related_name='origins', to='champions.champion'),
        ),
    ]
