# Generated by Django 5.0.2 on 2024-03-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergies', '0005_alter_job_champion_alter_origin_champion'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='avartar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='origin',
            name='avartar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
