# Generated by Django 5.0.2 on 2024-05-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergies', '0005_remove_trait_stats_1_remove_trait_stats_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='key',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trait',
            name='stats1',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
