# Generated by Django 5.0.2 on 2024-03-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synergies', '0006_job_avartar_origin_avartar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='origin',
            old_name='descriptoin',
            new_name='description',
        ),
    ]
