# Generated by Django 5.0.2 on 2024-06-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synergies", "0006_alter_trait_key_alter_trait_stats1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trait", name="ingameKey", field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="trait", name="name", field=models.CharField(max_length=20),
        ),
    ]
