# Generated by Django 5.0.2 on 2024-03-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synergies', '0007_rename_descriptoin_origin_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='descriptoin',
            new_name='description',
        ),
    ]
