# Generated by Django 5.0.2 on 2024-03-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synergies', '0008_rename_descriptoin_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='avartar',
        ),
        migrations.RemoveField(
            model_name='origin',
            name='avartar',
        ),
    ]
