# Generated by Django 4.0.10 on 2024-09-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergies', '0008_set11trait_set12trait_delete_trait'),
    ]

    operations = [
        migrations.AddField(
            model_name='set12trait',
            name='isHidden',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
