# Generated by Django 4.0.10 on 2024-09-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergies', '0009_set12trait_ishidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set12trait',
            name='isHidden',
            field=models.BooleanField(default=False),
        ),
    ]
