# Generated by Django 5.0.2 on 2024-03-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synergies", "0009_remove_job_avartar_remove_origin_avartar"),
    ]

    operations = [
        migrations.AddField(
            model_name="job", name="effect", field=models.TextField(default="직업효과"),
        ),
        migrations.AddField(
            model_name="origin", name="effect", field=models.TextField(default="계열효과"),
        ),
        migrations.AlterField(
            model_name="job", name="description", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="origin", name="description", field=models.TextField(),
        ),
    ]
