# Generated by Django 5.0.2 on 2024-03-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synergies', '0010_job_effect_origin_effect_alter_job_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='champion',
        ),
        migrations.RemoveField(
            model_name='origin',
            name='champion',
        ),
    ]
