# Generated by Django 5.0.2 on 2024-03-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0008_skill_effect_alter_skill_description'),
        ('synergies', '0011_remove_job_champion_remove_origin_champion'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='champion',
            field=models.ManyToManyField(related_name='jobs', to='champions.champion'),
        ),
        migrations.AddField(
            model_name='origin',
            name='champion',
            field=models.ManyToManyField(related_name='origins', to='champions.champion'),
        ),
    ]
