# Generated by Django 5.0.2 on 2024-03-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergies', '0013_remove_job_champion_remove_origin_champion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='effect',
        ),
        migrations.RemoveField(
            model_name='origin',
            name='effect',
        ),
        migrations.AddField(
            model_name='job',
            name='effect_1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='effect_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='effect_3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='effect_4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='origin',
            name='effect_1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='origin',
            name='effect_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='origin',
            name='effect_3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='origin',
            name='effect_4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='origin',
            name='effect_5',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='origin',
            name='effect_6',
            field=models.TextField(null=True),
        ),
    ]
