# Generated by Django 5.0.2 on 2024-03-16 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergies', '0014_remove_job_effect_remove_origin_effect_job_effect_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynergyStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack', models.CharField(choices=[('1', '1'), ('2/4', '2/4'), ('2/3/4', '2/3/4'), ('2/3/4/5', '2/3/4/5'), ('2/4/6', '2/4/6'), ('2/4/6/8', '2/4/6/8'), ('2/3/4/5/6/7', '2/3/4/5/6/7'), ('3/5', '3/5'), ('3/5/7', '3/5/7'), ('3/5/7/10', '3/5/7/10')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SynergyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('b/s/g', 'B/S/G'), ('b/p/g', 'B/P/G'), ('b/s/g/p', 'B/S/G/P'), ('b/s/s/s/g/g', 'B/S/S/G/G'), ('b/g', 'B/G'), ('unique', 'UNIQUE'), ('none', 'NONE')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='stack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='synergies.synergystack'),
        ),
        migrations.AddField(
            model_name='origin',
            name='stack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='synergies.synergystack'),
        ),
        migrations.AddField(
            model_name='job',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='synergies.synergytier'),
        ),
        migrations.AddField(
            model_name='origin',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='synergies.synergytier'),
        ),
    ]
