# Generated by Django 5.0.2 on 2024-03-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergies', '0015_synergystack_synergytier_job_stack_origin_stack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='effect_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='effect_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='effect_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='effect_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='origin',
            name='effect_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='origin',
            name='effect_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='origin',
            name='effect_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='origin',
            name='effect_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='origin',
            name='effect_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='origin',
            name='effect_6',
            field=models.TextField(blank=True, null=True),
        ),
    ]
