# Generated by Django 5.0.2 on 2024-03-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergies', '0016_alter_job_effect_1_alter_job_effect_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synergytier',
            name='name',
            field=models.CharField(choices=[('b/s/g', 'B/S/G'), ('b/g/p', 'B/G/P'), ('b/s/g/p', 'B/S/G/P'), ('b/s/s/s/g/g', 'B/S/S/G/G'), ('b/g', 'B/G'), ('unique', 'UNIQUE'), ('none', 'NONE')], max_length=20),
        ),
    ]
