# Generated by Django 5.0.2 on 2024-03-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_itemrecipies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrecipies',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
