# Generated by Django 5.0.2 on 2024-03-16 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_itemrecipies_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemRecipies',
            new_name='ItemRecipe',
        ),
    ]
