# Generated by Django 5.0.2 on 2024-03-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_itemrecipe_result_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='composition1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='composition2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.TextField(choices=[('basic', 'Basic'), ('normal', 'Normal'), ('emblem', 'Emblem'), ('support', 'Support'), ('artifact', 'Artifact'), ('radiant', 'Radiant')], default='NORMAL'),
        ),
        migrations.DeleteModel(
            name='ItemRecipe',
        ),
    ]
