# Generated by Django 5.0.2 on 2024-03-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_item_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inGameKey',
            field=models.CharField(default='TFT_', max_length=40),
        ),
    ]
