# Generated by Django 5.0.2 on 2024-05-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_alter_item_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
        migrations.AddField(
            model_name='item',
            name='tag1',
            field=models.TextField(blank=True, choices=[('basic', 'Basic'), ('normal', 'Normal'), ('emblem', 'Emblem'), ('support', 'Support'), ('artifact', 'Artifact'), ('radiant', 'Radiant'), ('etc', 'Etc')], default='Normal', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tag2',
            field=models.TextField(blank=True, choices=[('basic', 'Basic'), ('normal', 'Normal'), ('emblem', 'Emblem'), ('support', 'Support'), ('artifact', 'Artifact'), ('radiant', 'Radiant'), ('etc', 'Etc')], default='Normal', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tag3',
            field=models.TextField(blank=True, choices=[('basic', 'Basic'), ('normal', 'Normal'), ('emblem', 'Emblem'), ('support', 'Support'), ('artifact', 'Artifact'), ('radiant', 'Radiant'), ('etc', 'Etc')], default='Normal', null=True),
        ),
    ]
