# Generated by Django 5.0.2 on 2024-05-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_remove_item_tags_item_tag1_item_tag2_item_tag3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tag1',
            field=models.TextField(blank=True, choices=[('basic', 'Basic'), ('normal', 'Normal'), ('emblem', 'Emblem'), ('support', 'Support'), ('artifact', 'Artifact'), ('radiant', 'Radiant'), ('etc', 'Etc')], null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag2',
            field=models.TextField(blank=True, choices=[('basic', 'Basic'), ('normal', 'Normal'), ('emblem', 'Emblem'), ('support', 'Support'), ('artifact', 'Artifact'), ('radiant', 'Radiant'), ('etc', 'Etc')], null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag3',
            field=models.TextField(blank=True, choices=[('basic', 'Basic'), ('normal', 'Normal'), ('emblem', 'Emblem'), ('support', 'Support'), ('artifact', 'Artifact'), ('radiant', 'Radiant'), ('etc', 'Etc')], null=True),
        ),
    ]
