# Generated by Django 5.0.2 on 2024-05-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_alter_item_tag1_alter_item_tag2_alter_item_tag3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='inGameKey',
            new_name='ingameKey',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='effect',
            new_name='shortDesc',
        ),
        migrations.RemoveField(
            model_name='item',
            name='generableItem',
        ),
        migrations.AddField(
            model_name='item',
            name='isArtifact',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='isEmblem',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='isFromItem',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='isNew',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='isNormal',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='isRadiant',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='isSupport',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='isUnique',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag1',
            field=models.TextField(blank=True, choices=[('fromitem', 'Fromitem'), ('normal', 'Normal'), ('emblem', 'Emblem'), ('support', 'Support'), ('artifact', 'Artifact'), ('radiant', 'Radiant'), ('unique', 'Unique'), ('new', 'New')], null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag2',
            field=models.TextField(blank=True, choices=[('fromitem', 'Fromitem'), ('normal', 'Normal'), ('emblem', 'Emblem'), ('support', 'Support'), ('artifact', 'Artifact'), ('radiant', 'Radiant'), ('unique', 'Unique'), ('new', 'New')], null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag3',
            field=models.TextField(blank=True, choices=[('fromitem', 'Fromitem'), ('normal', 'Normal'), ('emblem', 'Emblem'), ('support', 'Support'), ('artifact', 'Artifact'), ('radiant', 'Radiant'), ('unique', 'Unique'), ('new', 'New')], null=True),
        ),
    ]
