# Generated by Django 5.0.2 on 2024-05-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_rename_ingamekey_item_ingamekey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='isArtifact',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='isEmblem',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='isFromItem',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='isNew',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='isNormal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='isRadiant',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='isSupport',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='isUnique',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
