# Generated by Django 5.0.2 on 2024-06-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_alter_item_imageurl_alter_item_isartifact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imageUrl',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='key',
            field=models.CharField(default='Eng_Key', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag1',
            field=models.TextField(blank=True, choices=[('fromitem', 'Fromitem'), ('normal', 'Normal'), ('emblem', 'Emblem'), ('support', 'Support'), ('artifact', 'Artifact'), ('radiant', 'Radiant'), ('unique', 'Unique'), ('new', 'New'), ('inkshadw', 'Inkshadw'), ('storyweaver', 'Storyweaver')], null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag2',
            field=models.TextField(blank=True, choices=[('fromitem', 'Fromitem'), ('normal', 'Normal'), ('emblem', 'Emblem'), ('support', 'Support'), ('artifact', 'Artifact'), ('radiant', 'Radiant'), ('unique', 'Unique'), ('new', 'New'), ('inkshadw', 'Inkshadw'), ('storyweaver', 'Storyweaver')], null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag3',
            field=models.TextField(blank=True, choices=[('fromitem', 'Fromitem'), ('normal', 'Normal'), ('emblem', 'Emblem'), ('support', 'Support'), ('artifact', 'Artifact'), ('radiant', 'Radiant'), ('unique', 'Unique'), ('new', 'New'), ('inkshadw', 'Inkshadw'), ('storyweaver', 'Storyweaver')], null=True),
        ),
    ]
