# Generated by Django 5.0.2 on 2024-06-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_alter_item_imageurl_alter_item_key_alter_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ingameKey',
            field=models.CharField(default='TFT_', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag1',
            field=models.TextField(blank=True, choices=[('fromitem', 'Fromitem'), ('normal', 'Normal'), ('emblem', 'Emblem'), ('support', 'Support'), ('artifact', 'Artifact'), ('radiant', 'Radiant'), ('unique', 'Unique'), ('new', 'New')], null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag2',
            field=models.TextField(blank=True, choices=[('fromitem', 'Fromitem'), ('normal', 'Normal'), ('emblem', 'Emblem'), ('support', 'Support'), ('artifact', 'Artifact'), ('radiant', 'Radiant'), ('unique', 'Unique'), ('new', 'New')], null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag3',
            field=models.TextField(blank=True, choices=[('fromitem', 'Fromitem'), ('normal', 'Normal'), ('emblem', 'Emblem'), ('support', 'Support'), ('artifact', 'Artifact'), ('radiant', 'Radiant'), ('unique', 'Unique'), ('new', 'New')], null=True),
        ),
    ]
