# Generated by Django 5.0.2 on 2024-07-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0005_set11comp_set11compelement_set11itemusage_and_more'),
        ('items', '0019_alter_item_ingamekey_alter_item_tag1_alter_item_tag2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set11Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='Eng_Key', max_length=100)),
                ('ingameKey', models.CharField(default='TFT_', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('shortDesc', models.TextField(blank=True)),
                ('imageUrl', models.URLField(default='')),
                ('composition1', models.CharField(blank=True, max_length=50)),
                ('composition2', models.CharField(blank=True, max_length=50)),
                ('isFromItem', models.BooleanField(blank=True, null=True)),
                ('isNormal', models.BooleanField(blank=True, null=True)),
                ('isEmblem', models.BooleanField(blank=True, null=True)),
                ('isSupport', models.BooleanField(blank=True, null=True)),
                ('isArtifact', models.BooleanField(blank=True, null=True)),
                ('isRadiant', models.BooleanField(blank=True, null=True)),
                ('isUnique', models.BooleanField(blank=True, null=True)),
                ('isNew', models.BooleanField(blank=True, null=True)),
                ('tag1', models.TextField(blank=True, choices=[('fromitem', 'Fromitem'), ('normal', 'Normal'), ('emblem', 'Emblem'), ('support', 'Support'), ('artifact', 'Artifact'), ('radiant', 'Radiant'), ('unique', 'Unique'), ('new', 'New')], null=True)),
                ('tag2', models.TextField(blank=True, choices=[('fromitem', 'Fromitem'), ('normal', 'Normal'), ('emblem', 'Emblem'), ('support', 'Support'), ('artifact', 'Artifact'), ('radiant', 'Radiant'), ('unique', 'Unique'), ('new', 'New')], null=True)),
                ('tag3', models.TextField(blank=True, choices=[('fromitem', 'Fromitem'), ('normal', 'Normal'), ('emblem', 'Emblem'), ('support', 'Support'), ('artifact', 'Artifact'), ('radiant', 'Radiant'), ('unique', 'Unique'), ('new', 'New')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Set12Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='Eng_Key', max_length=100)),
                ('ingameKey', models.CharField(default='TFT_', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('shortDesc', models.TextField(blank=True)),
                ('imageUrl', models.URLField(default='')),
                ('composition1', models.CharField(blank=True, max_length=50)),
                ('composition2', models.CharField(blank=True, max_length=50)),
                ('isFromItem', models.BooleanField(blank=True, null=True)),
                ('isNormal', models.BooleanField(blank=True, null=True)),
                ('isEmblem', models.BooleanField(blank=True, null=True)),
                ('isSupport', models.BooleanField(blank=True, null=True)),
                ('isArtifact', models.BooleanField(blank=True, null=True)),
                ('isRadiant', models.BooleanField(blank=True, null=True)),
                ('isUnique', models.BooleanField(blank=True, null=True)),
                ('isNew', models.BooleanField(blank=True, null=True)),
                ('tag1', models.TextField(blank=True, choices=[('fromitem', 'Fromitem'), ('normal', 'Normal'), ('emblem', 'Emblem'), ('support', 'Support'), ('artifact', 'Artifact'), ('radiant', 'Radiant'), ('unique', 'Unique'), ('new', 'New')], null=True)),
                ('tag2', models.TextField(blank=True, choices=[('fromitem', 'Fromitem'), ('normal', 'Normal'), ('emblem', 'Emblem'), ('support', 'Support'), ('artifact', 'Artifact'), ('radiant', 'Radiant'), ('unique', 'Unique'), ('new', 'New')], null=True)),
                ('tag3', models.TextField(blank=True, choices=[('fromitem', 'Fromitem'), ('normal', 'Normal'), ('emblem', 'Emblem'), ('support', 'Support'), ('artifact', 'Artifact'), ('radiant', 'Radiant'), ('unique', 'Unique'), ('new', 'New')], null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
