# Generated by Django 4.0.10 on 2024-09-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_set11item_set12item_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='set12item',
            name='isHidden',
            field=models.BooleanField(default=False),
        ),
    ]
