# Generated by Django 4.0.10 on 2024-09-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_set12item_ishidden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set12item',
            old_name='description',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='set12item',
            name='tag1',
        ),
        migrations.RemoveField(
            model_name='set12item',
            name='tag2',
        ),
        migrations.RemoveField(
            model_name='set12item',
            name='tag3',
        ),
        migrations.AddField(
            model_name='set12item',
            name='affectedTraitKey',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='set12item',
            name='fromDesc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='set12item',
            name='ingameIcon',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='set12item',
            name='imageUrl',
            field=models.URLField(),
        ),
    ]
