# Generated by Django 5.0.2 on 2024-03-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('champions', '0007_remove_champion_avatar_remove_skill_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('origin', models.PositiveIntegerField()),
                ('job', models.PositiveIntegerField()),
                ('cost', models.PositiveIntegerField()),
                ('champion', models.ManyToManyField(related_name='comps', to='champions.champion')),
            ],
        ),
    ]
