# Generated by Django 5.0.2 on 2024-04-30 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('champions', '0001_initial'),
        ('items', '0012_alter_item_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championLevelChoice', models.IntegerField(choices=[(1, 'oneStar'), (2, 'twoStar'), (3, 'threeStar')], default=2)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_comps', to='champions.champion')),
                ('recommendedItem1', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='item_comps_1', to='items.item')),
                ('recommendedItem2', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='item_comps_2', to='items.item')),
                ('recommendedItem3', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='item_comps_3', to='items.item')),
            ],
        ),
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('elements', models.ManyToManyField(related_name='comp_element', to='comps.compelement')),
            ],
        ),
    ]
