# Generated by Django 5.0.2 on 2024-03-08 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comp',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='job',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='origin',
        ),
    ]
