# Generated by Django 5.0.2 on 2024-06-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='is_blind',
            field=models.BooleanField(default=False),
        ),
    ]
