# Generated by Django 5.0.2 on 2024-03-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0002_remove_comp_cost_remove_comp_job_remove_comp_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comp',
            old_name='champion',
            new_name='champions',
        ),
    ]
