# Generated by Django 5.0.2 on 2024-03-25 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0008_skill_effect_alter_skill_description'),
        ('comps', '0003_rename_champion_comp_champions'),
        ('items', '0012_alter_item_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championLevelChoice', models.IntegerField(choices=[(1, 'oneStar'), (2, 'twoStar'), (3, 'threeStar')], default=2)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_comps', to='champions.champion')),
                ('recommendedItem1', models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, related_name='item_comps_1', to='items.item')),
                ('recommendedItem2', models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, related_name='item_comps_2', to='items.item')),
                ('recommendedItem3', models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, related_name='item_comps_3', to='items.item')),
            ],
        ),
        migrations.AddField(
            model_name='comp',
            name='elements',
            field=models.ManyToManyField(related_name='comp_element', to='comps.compelement'),
        ),
    ]
