# Generated by Django 5.0.2 on 2024-07-15 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0002_set11champion_set12champion'),
        ('comps', '0004_rename_metadecks_metadeck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set11Comp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_blind', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Set11CompElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championLevelChoice', models.IntegerField(choices=[(1, 'oneStar'), (2, 'twoStar'), (3, 'threeStar')], default=2)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_comps', to='champions.set11champion')),
            ],
        ),
        migrations.CreateModel(
            name='Set11ItemUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usages', models.JSONField(default=dict, verbose_name='json')),
            ],
        ),
        migrations.CreateModel(
            name='Set11MetaDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('decks', models.JSONField(default=dict, verbose_name='json')),
            ],
        ),
        migrations.CreateModel(
            name='Set12Comp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_blind', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Set12CompElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championLevelChoice', models.IntegerField(choices=[(1, 'oneStar'), (2, 'twoStar'), (3, 'threeStar')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Set12ItemUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usages', models.JSONField(default=dict, verbose_name='json')),
            ],
        ),
        migrations.CreateModel(
            name='Set12MetaDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('decks', models.JSONField(default=dict, verbose_name='json')),
            ],
        ),
        migrations.RemoveField(
            model_name='comp',
            name='elements',
        ),
        migrations.RemoveField(
            model_name='compelement',
            name='champion',
        ),
        migrations.RemoveField(
            model_name='compelement',
            name='recommendedItem1',
        ),
        migrations.RemoveField(
            model_name='compelement',
            name='recommendedItem2',
        ),
        migrations.RemoveField(
            model_name='compelement',
            name='recommendedItem3',
        ),
        migrations.DeleteModel(
            name='ItemUsage',
        ),
        migrations.DeleteModel(
            name='MetaDeck',
        ),
    ]
