# Generated by Django 5.0.2 on 2024-03-25 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0004_compelement_comp_elements'),
        ('items', '0012_alter_item_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compelement',
            name='recommendedItem1',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='item_comps_1', to='items.item'),
        ),
        migrations.AlterField(
            model_name='compelement',
            name='recommendedItem2',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='item_comps_2', to='items.item'),
        ),
        migrations.AlterField(
            model_name='compelement',
            name='recommendedItem3',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='item_comps_3', to='items.item'),
        ),
    ]
