# Generated by Django 5.0.2 on 2024-07-15 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0003_delete_champion'),
        ('comps', '0005_set11comp_set11compelement_set11itemusage_and_more'),
        ('items', '0020_set11item_set12item_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='set11compelement',
            name='recommendedItem1',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='item_comps_1', to='items.set11item'),
        ),
        migrations.AddField(
            model_name='set11compelement',
            name='recommendedItem2',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='item_comps_2', to='items.set11item'),
        ),
        migrations.AddField(
            model_name='set11compelement',
            name='recommendedItem3',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='item_comps_3', to='items.set11item'),
        ),
        migrations.AddField(
            model_name='set11comp',
            name='elements',
            field=models.ManyToManyField(related_name='comp_element', to='comps.set11compelement'),
        ),
        migrations.AddField(
            model_name='set12compelement',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_comps', to='champions.set12champion'),
        ),
        migrations.AddField(
            model_name='set12compelement',
            name='recommendedItem1',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='item_comps_1', to='items.set12item'),
        ),
        migrations.AddField(
            model_name='set12compelement',
            name='recommendedItem2',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='item_comps_2', to='items.set12item'),
        ),
        migrations.AddField(
            model_name='set12compelement',
            name='recommendedItem3',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='item_comps_3', to='items.set12item'),
        ),
        migrations.AddField(
            model_name='set12comp',
            name='elements',
            field=models.ManyToManyField(related_name='comp_element', to='comps.set12compelement'),
        ),
        migrations.DeleteModel(
            name='Comp',
        ),
        migrations.DeleteModel(
            name='CompElement',
        ),
    ]
