# Generated by Django 5.0.2 on 2024-03-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0005_alter_compelement_recommendeditem1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compelement',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
