# Generated by Django 5.0.2 on 2024-03-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0007_alter_compelement_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compelement',
            name='name',
        ),
        migrations.AddField(
            model_name='compelement',
            name='ele_name',
            field=models.TextField(default=None, null=True),
        ),
    ]
