# Generated by Django 5.0.2 on 2024-03-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0008_remove_compelement_name_compelement_ele_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compelement',
            name='ele_name',
            field=models.TextField(blank=True, default=None),
        ),
    ]
