# Generated by Django 5.0.2 on 2024-03-26 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0011_alter_compelement_ele_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compelement',
            name='ele_name',
        ),
    ]
