# Generated by Django 5.0.2 on 2024-03-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0012_remove_compelement_ele_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='compelement',
            name='ele_name',
            field=models.TextField(blank=True, default='이름'),
        ),
    ]
