# Generated by Django 5.0.2 on 2024-03-06 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('augments', '0003_augment_image'),
        ('champions', '0006_remove_champion_dps'),
        ('portals', '0003_portal_image'),
        ('synergies', '0008_rename_descriptoin_job_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.URLField()),
                ('description', models.CharField(max_length=140)),
                ('augment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='augments.augment')),
                ('champion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='champions.champion')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='synergies.job')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='synergies.origin')),
                ('portal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portals.portal')),
            ],
        ),
    ]
