# Generated by Django 5.0.2 on 2024-03-06 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augments', '0004_remove_augment_image'),
        ('champions', '0007_remove_champion_avatar_remove_skill_avatar'),
        ('medias', '0001_initial'),
        ('portals', '0004_remove_portal_image'),
        ('synergies', '0009_remove_job_avartar_remove_origin_avartar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='augment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='augments.augment'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='champions.champion'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='synergies.job'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='synergies.origin'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portals.portal'),
        ),
    ]
