# Generated by Django 5.0.2 on 2024-03-07 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0007_remove_champion_avatar_remove_skill_avatar'),
        ('medias', '0002_alter_photo_augment_alter_photo_champion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='champions.skill'),
        ),
    ]
