# Generated by Django 5.0.2 on 2024-03-07 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0003_photo_skill'),
        ('synergies', '0009_remove_job_avartar_remove_origin_avartar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_photos', to='synergies.job'),
        ),
    ]
