# Generated by Django 5.0.2 on 2024-03-07 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0004_alter_photo_job'),
        ('synergies', '0009_remove_job_avartar_remove_origin_avartar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='synergies.job'),
        ),
    ]
