# Generated by Django 5.0.2 on 2024-03-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0006_photo_encounter'),
        ('medias', '0006_photo_item'),
    ]

    operations = [
    ]
