# Generated by Django 5.0.2 on 2024-03-16 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0008_alter_photo_portal'),
        ('portals', '0008_rename_portaltype_portaltype_portal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portals.portal'),
        ),
    ]
