# Generated by Django 5.0.2 on 2024-03-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0010_alter_photo_portal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='item',
        ),
    ]
