# Generated by Django 5.0.2 on 2024-03-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('synergies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cost', models.PositiveIntegerField()),
                ('synergies', models.ManyToManyField(to='synergies.synergy')),
            ],
        ),
    ]
