# Generated by Django 5.0.2 on 2024-03-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='attack_range',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='champion',
            name='attack_speed',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
        migrations.AddField(
            model_name='champion',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='champion',
            name='defense',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='champion',
            name='dps',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='champion',
            name='health',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='champion',
            name='magic_resistance',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='champion',
            name='offense_power',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
