# Generated by Django 5.0.2 on 2024-03-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('champions', '0001_initial'),
        ('synergies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='job',
            field=models.ManyToManyField(related_name='champions', to='synergies.job'),
        ),
        migrations.AddField(
            model_name='champion',
            name='origin',
            field=models.ManyToManyField(related_name='champions', to='synergies.origin'),
        ),
    ]
