# Generated by Django 5.0.2 on 2024-03-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0004_champion_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='max_mana',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='start_mana',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
