# Generated by Django 5.0.2 on 2024-03-05 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0005_skill_max_mana_skill_start_mana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='dps',
        ),
    ]
