# Generated by Django 5.0.2 on 2024-03-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("champions", "0007_remove_champion_avatar_remove_skill_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill", name="effect", field=models.TextField(default="스킬효과입력"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="description",
            field=models.TextField(default="스킬설명입력"),
        ),
    ]
