# Generated by Django 4.0.10 on 2024-09-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set12Charm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cost', models.IntegerField()),
                ('tier', models.PositiveIntegerField()),
                ('_key', models.CharField(max_length=100)),
                ('desc', models.TextField(default='이번 게임에서 얻는 마지막 증강이 골드 티어가 됩니다.', max_length=300)),
                ('imageUrl', models.URLField(default='https://cdn.dak.gg/tft/images2/charms/set12/charm-1.png')),
            ],
        ),
    ]
