# Generated by Django 4.0.10 on 2024-09-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set12charm',
            name='tier',
            field=models.DecimalField(decimal_places=1, max_digits=1),
        ),
    ]
